server:
  port: 8000
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force-response: true
API:
  REQUEST:
    URI: https://dapi.kakao.com/v2/local/search/keyword.json
    KEY: "04e8cb4517f26fb89660073342a5a53c"
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    username: sa
    password:
    #    driverClassName: org.h2.Driver
    driverClassName: org.h2.Driver
    sql-script-encoding: UTF-8
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        use_sql_comments: true
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
  messages:
    encoding: UTF-8
logging:
  level:
    info: trace
    jdbc:
      sqlonly: off
      sqltiming: info
      resultsettable: off
      audit: off
      resultset: off
      connection: off