server:
  port: 8000
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
      force-response: true
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
#    url: jdbc:h2:mem:testdb;MODE=MYSQL
    url: jdbc:mysql://localhost:33060/dinner?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: dinner
    password: 2JA2_Jg#2t63zwvZ
#    driverClassName: org.h2.Driver
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    sql-script-encoding: UTF-8
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
#        generate_statistics: true
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
  mvc:
    throw-exception-if-no-handler-found: true
    dispatch-options-request: false
logging:
  level:
    info: debug
    jdbc:
      sqlonly: off
      sqltiming: info
      resultsettable: off
      audit: off
      resultset: off
      connection: off
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
API:
  REQUEST:
    URI: https://dapi.kakao.com/v2/local/search/keyword.json
    KEY: "04e8cb4517f26fb89660073342a5a53c"
JWT:
  ISSUER: Dinner_Site
  SECRET-KEY: QqjcJV8*b_X7J5Q&